#!/usr/bin/env python3
"""Inspect MT10 entry variants generated by post9_resource_group_search.ensure_mt10."""

from __future__ import annotations

import os
import sys


ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
if ROOT not in sys.path:
    sys.path.insert(0, ROOT)
os.chdir(ROOT)

from scripts import compare_mt6_key_variant as forced
from scripts import post9_resource_group_search as rg


def main() -> None:
    _best, chain = forced.build_variant()
    before_mt6_key = next(item["entry"] for item in chain if item["label"] == "MT4 blueKey")
    before_mt9 = next(item["entry"] for item in chain if item["label"] == "MT7 yellowKey")

    for label, ent in [("before MT6 key", before_mt6_key), ("before MT9", before_mt9)]:
        variants = rg.ensure_mt10(ent)
        print(label)
        for idx, v in enumerate(variants, 1):
            mt6 = (9, 1) in v.get("collected", {}).get("MT6", frozenset())
            mt9 = (2, 2) in v.get("collected", {}).get("MT9", frozenset())
            print(
                f"  {idx}: HP={v['hp']} ATK={v['atk']} DEF={v['def']} "
                f"YK={v['yk']} BK={v['bk']} dmg={v.get('_dmg', 0)} "
                f"door={v.get('_yd', 0)}/{v.get('_bd', 0)}/{v.get('_rd', 0)} "
                f"mt6x9y1={mt6} mt9x2y2={mt9} rg={rg.resource_group_score(v)}"
            )


if __name__ == "__main__":
    main()
