#!/usr/bin/env python3
"""Guided 2-hour zone-3 search from slot26.

This wraps ``search_zone3_slot26_explore`` with a milestone-heavy scoring model.
The goal is to keep the generic replay legality checks while avoiding the broad
beam's tendency to spend the whole run collecting low-floor resources.

Comparison score remains simple: 1YK = 50HP = 100G. Shop actions are capped at
eight zone-3 ATK/DEF buys from slot26's ``times1=2`` state; HP shop buys are not
generated by the underlying explorer.
"""

from __future__ import annotations

import argparse
import importlib.util
import sys
from pathlib import Path
from typing import Any


ROOT = Path(__file__).resolve().parents[1]
BASE_PATH = ROOT / "scripts" / "search_zone3_slot26_explore.py"
OUT_JSON = ROOT / "outputs" / "results" / "zone3_slot26_guided_2h.json"
OUT_MD = ROOT / "outputs" / "reports" / "zone3_slot26_guided_2h.md"
OUT_LOG = ROOT / "outputs" / "logs" / "zone3_slot26_guided_2h_progress.log"


def load_base() -> Any:
    spec = importlib.util.spec_from_file_location("zone3_slot26_guided_base", BASE_PATH)
    if spec is None or spec.loader is None:
        raise RuntimeError(BASE_PATH)
    mod = importlib.util.module_from_spec(spec)
    sys.modules[spec.name] = mod
    spec.loader.exec_module(mod)
    return mod


base = load_base()
orig_special_actions = base.special_actions
orig_candidate_target_actions = base.candidate_target_actions


def shop_buys(g: Any) -> int:
    return max(0, int(g.state.get("times1", 2)) - 2)


def block_missing(g: Any, fid: str, pos: tuple[int, int], eid: str | None = None) -> bool:
    block = g.block_at(fid, pos)
    if block is None:
        return True
    return eid is not None and block.eid != eid


def has_sword3(g: Any) -> bool:
    return block_missing(g, "MT33", (10, 10), "sword3")


def sword_trap_done(g: Any) -> bool:
    done = g.state.get("special_done", set())
    if "mt33_sword_trap" in done:
        return True
    block_a = g.block_at("MT33", (10, 4))
    block_b = g.block_at("MT33", (10, 8))
    return bool(block_a and block_a.eid == "specialDoor" and block_b and block_b.eid == "specialDoor")


def has_shield3(g: Any) -> bool:
    return block_missing(g, "MT38", (2, 7), "shield3")


def mt32_event_done(g: Any) -> bool:
    floor = g.floors.get("MT32")
    if not floor:
        return False
    # The knight-captain event is an event tile, not a normal enemy block.
    # Before it fires, the vertical special doors at x6y2/x6y9 still exist.
    return floor.grid[2][6] == 0 and floor.grid[9][6] == 0


def mt2_oldman_done(g: Any) -> bool:
    return block_missing(g, "MT2", (11, 4), "oldman")


def mt2_thief_done(g: Any) -> bool:
    return block_missing(g, "MT2", (10, 11), "thief")


def milestone(g: Any) -> int:
    visited = g.state.get("visited", set())
    value = 0
    value += max((base.floor_no(fid) for fid in visited), default=31) * 300
    if "MT32" in visited:
        value += 20_000
    if mt32_event_done(g):
        value += 140_000
    value += min(shop_buys(g), 8) * 14_000
    if sword_trap_done(g):
        value += 20_000
    if has_sword3(g):
        value += 240_000
    if mt2_oldman_done(g):
        value += 130_000
    if mt2_thief_done(g):
        value += 70_000
    if "MT37" in visited:
        value += 70_000
    if "MT38" in visited:
        value += 70_000
    if has_shield3(g):
        value += 180_000
    if g.state.get("centerFly3"):
        value += 150_000
    if "MT40" in visited:
        value += 80_000
    if g.state.get("boss40") or block_missing(g, "MT40", (6, 1), "upFloor"):
        value += 360_000
    return value


def guided_item_value(eid: str, g: Any) -> int:
    hp = g.state["hp"]
    before_mt32 = not mt32_event_done(g)
    before_sword = not has_sword3(g)
    if eid == "sword3":
        return 80_000
    if eid == "shield3":
        return 85_000
    if eid == "centerFly3":
        return 90_000
    if eid == "blueGem":
        return 4_500 if before_sword else 2_600
    if eid == "redGem":
        return 4_200 if before_sword else 2_500
    if eid == "blueKey":
        return 3_500
    if eid == "redKey":
        return 4_000
    if eid == "yellowKey":
        return 1_600 if g.state["yk"] < 3 else 900
    if eid == "bluePotion":
        if before_mt32 or (before_sword and hp < 900):
            return 7_500
        if has_sword3(g) and not mt2_oldman_done(g) and hp < 700:
            return 6_500
        return 1_000
    if eid == "redPotion":
        if before_mt32 or (before_sword and hp < 700):
            return 3_500
        if has_sword3(g) and not mt2_oldman_done(g) and hp < 500:
            return 3_200
        return 650
    return 0


def guided_enemy_value(fid: str, eid: str, dmg: int | float, g: Any) -> int:
    if dmg == float("inf") or g.state["hp"] - int(dmg) <= 0:
        return -10**9
    enemy = g.enemies[eid]
    money = int(enemy["money"])
    need_shop_gold = shop_buys(g) < 8 and g.state["gold"] < base.p.shop_cost(g.state["times1"])
    progress_bonus = 1_500 if base.floor_no(fid) >= 31 else 300
    if need_shop_gold:
        progress_bonus += 1_800
    if dmg == 0 and not need_shop_gold:
        return money * 5 + progress_bonus // 3
    return money * (26 if need_shop_gold else 13) + progress_bonus - int(dmg) * 2


def guided_score(g: Any) -> int:
    s = g.state
    stock = s["hp"] + s["yk"] * 50 + s["bk"] * 200 + s["gold"] * 0.5
    if not has_sword3(g):
        stats = s["atk"] * 780 + s["def"] * 330
        if s["atk"] < 110:
            stats -= (110 - s["atk"]) * 180
    else:
        stats = s["atk"] * 520 + s["def"] * 410
    hp_bonus = min(s["hp"], 1200) * (3 if not has_sword3(g) or not mt2_oldman_done(g) else 1)
    shop_goal = min(shop_buys(g), 8) * 8_000
    over_shop_penalty = max(0, shop_buys(g) - 8) * 100_000
    door_penalty = s["yd"] * 45 + s["bd"] * 160 + s["rd"] * 300
    return int(milestone(g) + stock + stats + hp_bonus + shop_goal - s["dmg"] * 0.7 - door_penalty - over_shop_penalty)


def guided_goal_score(g: Any) -> int:
    s = g.state
    stock = s["hp"] + s["yk"] * 50 + s["bk"] * 200 + s["gold"] * 0.5
    return int(stock + s["atk"] * 260 + s["def"] * 280 - s["dmg"] - s["yd"] * 50 - s["bd"] * 200 - s["rd"] * 350)


def guided_state_bucket(g: Any) -> tuple[Any, ...]:
    s = g.state
    visited_max = max((base.floor_no(fid) for fid in s.get("visited", {"MT31"})), default=31)
    return (
        visited_max,
        mt32_event_done(g),
        has_sword3(g),
        mt2_oldman_done(g),
        mt2_thief_done(g),
        has_shield3(g),
        bool(s.get("centerFly3")),
        bool(s.get("boss40")),
        s["floor"],
        s["atk"] // 4,
        s["def"] // 4,
        min(s["hp"], 2000) // 100,
        s["yk"],
        s["bk"],
        s["rk"],
        min(shop_buys(g), 9),
        min(5000, max(-1000, s["gold"])) // 100,
    )


def guided_special_actions(g: Any) -> list[dict[str, Any]]:
    actions = orig_special_actions(g)
    actions = [a for a in actions if not a["label"].startswith("MT32:shop:")]
    if base.can_fly_to(g, "MT32") and not mt32_event_done(g):
        def mt32_event(candidate: Any) -> bool:
            before_errors = len(candidate.errors)
            if candidate.state["floor"] != "MT32":
                candidate.fly("MT32")
            candidate.go_to("MT32", 6, 10, "32F knight-captain event tile")
            if len(candidate.errors) != before_errors:
                return False
            before_steps = len(candidate.steps)
            candidate.event_mt32_yellow_knight()
            candidate.state.setdefault("special_done", set()).add("mt32_yellow_knight")
            return len(candidate.errors) == before_errors and len(candidate.steps) > before_steps

        actions.append(
            {
                "label": "MT32:event:yellowKnightTile",
                "kind": "event",
                "priority": 80_000,
                "apply": mt32_event,
            }
        )
    if not mt32_event_done(g):
        actions = [a for a in actions if a["label"] != "MT32:upFloor->MT33"]
    if not has_sword3(g):
        actions = [a for a in actions if not a["label"].startswith("MT2:event:")]
        actions = [a for a in actions if not a["label"].startswith("MT35:event:")]
    if has_sword3(g):
        actions = [a for a in actions if "swordTrap" not in a["label"]]
    if shop_buys(g) >= 8:
        actions = [a for a in actions if not a["label"].startswith("MT32:shop:")]
    elif mt32_event_done(g) and base.can_fly_to(g, "MT32"):
        cost = base.p.shop_cost(g.state["times1"])
        if g.state["gold"] >= cost:
            if not has_sword3(g) and g.state["atk"] < 110:
                shop_order = (("atk", 86_000), ("def", 62_000))
            elif not has_sword3(g):
                shop_order = (("atk", 72_000), ("def", 70_000))
            else:
                shop_order = (("atk", 68_000), ("def", 67_000))
            for kind, base_priority in shop_order:
                def make_shop(k: str) -> Any:
                    def shop(candidate: Any) -> bool:
                        before_errors = len(candidate.errors)
                        before_steps = len(candidate.steps)
                        if candidate.state["floor"] != "MT32":
                            if base.floor_no(candidate.state["floor"]) > 32 and base.can_fly_to(candidate, "MT31"):
                                candidate.fly("MT31")
                            candidate.fly("MT32")
                        candidate.go_to("MT32", 10, 10, f"32F guided shop {k}")
                        if len(candidate.errors) != before_errors:
                            return False
                        if candidate.state["gold"] < base.p.shop_cost(candidate.state["times1"]):
                            return False
                        candidate.buy_shop(k, 1)
                        return len(candidate.errors) == before_errors and len(candidate.steps) > before_steps

                    return shop

                actions.append(
                    {
                        "label": f"MT32:guidedShop:{kind}:cost{cost}",
                        "kind": "shop",
                        "priority": base_priority - cost // 3 + shop_buys(g) * 4_000,
                        "apply": make_shop(kind),
                    }
                )
    # Raise event/progress actions above incidental resource grabs.
    for action in actions:
        label = action["label"]
        if "yellowKnight" in label:
            action["priority"] += 30_000
        elif "swordTrap" in label:
            action["priority"] += 28_000
        elif "oldman1000G" in label:
            action["priority"] += 35_000
        elif "thiefOpen35" in label or "thiefDepart" in label:
            action["priority"] += 20_000
        elif "shop:atk" in label or "shop:def" in label:
            action["priority"] += 18_000
        elif "sell1YK" in label and shop_buys(g) < 8:
            next_cost = base.p.shop_cost(g.state["times1"])
            if g.state["gold"] < next_cost:
                action["priority"] += 35_000
        elif "upFloor" in label:
            action["priority"] += 12_000
    return actions


def guided_candidate_target_actions(g: Any, max_targets: int) -> list[dict[str, Any]]:
    actions = orig_candidate_target_actions(g, max_targets * 2)
    filtered = []
    for action in actions:
        label = action["label"]
        if label.startswith("MT33:x10y10:sword3") and not sword_trap_done(g):
            continue
        filtered.append(action)
        if len(filtered) >= max_targets:
            break
    return filtered


def install_guidance() -> None:
    base.item_value = guided_item_value
    base.enemy_value = guided_enemy_value
    base.score = guided_score
    base.goal_score = guided_goal_score
    base.state_bucket = guided_state_bucket
    base.special_actions = guided_special_actions
    base.candidate_target_actions = guided_candidate_target_actions


def main() -> int:
    install_guidance()
    parser = argparse.ArgumentParser()
    parser.add_argument("--snapshot", type=Path, default=base.DEFAULT_SNAPSHOT)
    parser.add_argument("--time-limit-seconds", type=float, default=7200)
    parser.add_argument("--beam", type=int, default=260)
    parser.add_argument("--targets-per-state", type=int, default=34)
    parser.add_argument("--actions-per-state", type=int, default=54)
    parser.add_argument("--max-depth", type=int, default=360)
    parser.add_argument("--report-interval", type=float, default=60)
    parser.add_argument("--progress-log", type=Path, default=OUT_LOG)
    parser.add_argument("--out-json", type=Path, default=OUT_JSON)
    parser.add_argument("--out-md", type=Path, default=OUT_MD)
    parser.add_argument("--daemon-stdout", type=Path, default=None)
    parser.add_argument("--daemon-stderr", type=Path, default=None)
    args = parser.parse_args()
    if args.daemon_stdout:
        args.daemon_stdout.parent.mkdir(parents=True, exist_ok=True)
        sys.stdout = args.daemon_stdout.open("a", encoding="utf-8", buffering=1)
    if args.daemon_stderr:
        args.daemon_stderr.parent.mkdir(parents=True, exist_ok=True)
        sys.stderr = args.daemon_stderr.open("a", encoding="utf-8", buffering=1)
    data = base.explore(args)
    base.write_report(data, args.out_json, args.out_md)
    print(f"wrote {args.out_json}")
    print(f"wrote {args.out_md}")
    if data.get("best_goal"):
        print("best_goal", data["best_goal"]["state_text"])
    else:
        print("best_goal not found")
    if data.get("best_any"):
        print("best_any", data["best_any"]["state_text"])
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
